name: Restart Kaggle Strike
on:
  schedule:
    - cron: '0 */11 * * *'
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Kaggle API
        run: pip install kaggle

      - name: Inject Secrets and Push
        env:
          # FORCING THE API TO READ THE TOKEN AS THE KEY
          KAGGLE_USERNAME: "praveermandal" # Your actual Kaggle Username
          KAGGLE_KEY: "KGAT_c6052a498590079b2f18752ad8832470" # Paste your KGAT token here directly or use ${{ secrets.KAGGLE_API_TOKEN }}
        run: |
          # 1. Swap the placeholders in your script
          sed -i "s|REPLACE_COOKIE|${{ secrets.INSTA_COOKIE }}|g" prvr_script.py
          sed -i "s|REPLACE_THREAD|${{ secrets.THREAD_ID }}|g" prvr_script.py
          sed -i "s|REPLACE_NAME|${{ secrets.TARGET_NAME }}|g" prvr_script.py
          
          # 2. Push to Kaggle
          kaggle kernels push -p .
